### ISSUE TITLE
How to make changes without creating a new PR?

### ISSUE THREAD

**Issue by ashjtan** [education/graduation#2281]
The instructions in the README say

> Those who have already submitted a pull request, is on review or pending changes you can still get added to the yearbook by **submitted those changes in the pull request you already have (without creating a new PR).**

However, there doesn't seem to be an option (at least not an obvious one) to reopen the PR after it is closed. I and many others have just opened new PRs with our changes and linked them in a comment. Am I missing something about how to reopen the PR?

**Comment by puf17640** [comment]
You can either edit your comment on the PR (by clicking the 3 dots on the upper right of each comment) or if you want to make changes to the uploaded files, you can either just edit them in the GitHub Online Editor or you can just add changes locally, create a commit and then push again (all new commits will be added to your open PR)

**Comment by ashjtan** [comment]
> (all new commits will be added to your open PR)

Adding the changes and pushing them would be ideal, but what about when the PR is already closed? That's how it's been handled so far when there are any problems with the current PR. Since my old PR was closed, my commits weren't tracked, so I had to open a new PR.

**Comment by laiyenju** [comment]
I have the same problem to reopen the closed pull request.
There's no button to reopen it. Did I missed some steps? Need help.

<img width="781" alt="Screen Shot 2020-05-23 at 2 28 22 PM" src="https://user-images.githubusercontent.com/29245400/82723453-a9f2a100-9d01-11ea-9a13-26debc02b0a6.png">

**Comment by puf17640** [comment]
@juanpflores Please do not close issues when you request changes, use the "request changes" feature, else this will create a lot more work to be done.

**Comment by puf17640** [comment]
**issue can be closed**
