### ISSUE TITLE
why our pull request is not get reviewed yet

### ISSUE THREAD

**Issue by dilipkary** [education/graduation#2314]
I have seen there are many of the pull requests after the mine is closed. so there is some discrimination I think.
 thank you for doing such things.
If don't want to review don't send mail for participating in it..
I am very disappointed with this. 
Thank you.
@juanpflores

**Comment by Mohammed-Shoaib** [comment]
Hey @dilipkary,

I am sorry you are disappointed. There are many pull requests to review (**~2000**) :mag:

Please give the maintainers some time. They are working very hard! :hourglass_flowing_sand:

I hope you do not feel saddened by this, let's make our graduation awesome! :mortar_board: :tada:

**Comment by dilipkary** [comment]
Yes, I see but at the time I made the request there is less than 1000 request and today I see that the requests after mine that is request numbered above 2000 are get reviewed. 
That's why I am disappointed because it is not first come first serve.

**Comment by puf17640** [comment]
> Yes, I see but at the time I made the request there is less than 1000 request and today I see that the requests after mine that is request numbered above 2000 are get reviewed.
> That's why I am disappointed because it is not first come first serve.

Does it really matter when you are added to the yearbook?

**Comment by brianxfury** [comment]
@dilipkary I noticed that some recent PRs got accepted while my PR was 3 days ago.

**Comment by wrik003** [comment]
@puf17640 I guess folks are just a tad bit anxious.

@dilipkary and @brianxfury keep faith. I'm sure @juanpflores and team are hard at it.

**Comment by dilipkary** [comment]
@puf17640 it doesn't matter but preferences given over country vice its not good. 
I am watching the closed pull requests and many are from other countries. but who made early request have to wait more it is not good.
I have seen a selected pull request merge.

**Comment by UtkarshChaurasia** [comment]
@dilipkary even I am having the same issue. My PR number is #663 but still, it is not reviewed yet.

**Comment by shoebkhan30** [comment]
same for me my PR is not reviewed no. is #2354

**Comment by jasperchua99** [comment]
mine too #2068

**Comment by puf17640** [comment]
> same for me my PR is not reviewed no. is #2354 

you literally submitted your PR 1h ago, please allow some time for the reviewers.

**Comment by Aman22sharma** [comment]
@dilipkary I totally agree with you the same thing is happening to me. My PR #1570 is also not reviewed yet.

**Comment by dilipkary** [comment]
@puf17640 I Submitted my pr 3 days ago what about it.

**Comment by puf17640** [comment]
> @puf17640 I Submitted my pr 3 days ago what about it.

So did I, what are you trying to tell me? There is no need to rush or hurry.

**Comment by dilipkary** [comment]
@puf17640 I am not trying to say anything. pr merge statistics saying itself. I don't need to say anything.
by the way, I am just fed up this. 
Thank you for your concern. 👍

**Comment by Mohammed-Shoaib** [comment]
> @puf17640 it doesn't matter but preferences given over country vice its not good.

@dilipkary I think you are just over-thinking. I belong to the same ethnicity as you, the reviewers are trying their best. It's impossible to review **~2000** pull requests in a day. The event is scheduled on June 15th, if your pull request is not reviewed by then, you can raise an issue.

For now, I strongly feel you should give the reviewers time! There is nothing gained or lost if your pull request is approved early or later.

If you feel satisfied with this, please close this issue.

**Comment by dilipkary** [comment]
@Mohammed-Shoaib Thank you for supporting this thing which is going on 👍

**Comment by puf17640** [comment]
> > @puf17640 it doesn't matter but preferences given over country vice its not good.
> 
> @dilipkary I think you are just over-thinking. I belong to the same ethnicity as you, the reviewers are trying their best. It's impossible to review **~2000** pull requests in a day. The event is scheduled on June 15th, if your pull request is not reviewed by then, you can raise an issue.
> 
> For now, I strongly feel you should give the reviewers time! There is nothing gained or lost if your pull request is approved early or later.
> 
> If you feel satisfied with this, please close this issue.

I agree. It's innapropriate to make a hurry out of it, since, as you say, we all have to wait until June 15th anyway, and it's pretty rude to bring up such accusations just like that.

**Comment by dilipkary** [comment]
Thank you do as you all like to do I will not now even check my pr or it gets merged or not. 
I am just disappointed with this type of behaviour, a good code of conduct,  good policies.
Thank you.

**Comment by Vishal1297** [comment]
> Be patient everyone.

**Comment by wrik003** [comment]
@dilipkary @Mohammed-Shoaib @puf17640 let's end this, yeah? This is meant to be a fun event!

@dilipkary I'll peer-review your PR. Link me to it.

**Comment by dilipkary** [comment]
@wrik003 https://github.com/education/graduation/pull/806 this is my pr link
Thank you

**Comment by UtkarshChaurasia** [comment]
mine PR is #663

**Comment by mogalvanize** [comment]
👋 Hi all!  The Education Team, which includes everyone's favorite @juanpflores, is working extremely hard on this event and, of course, reviewing PRs.  They are reviewed in random order to ensure there is no bias.

**Comment by juanpflores** [comment]
![image](https://user-images.githubusercontent.com/6200135/82734222-27f18080-9cdf-11ea-9878-79bf9216e774.png)

Hey Everyone 👋 😞,
_Just getting everyone in the loop for this._ Thank you all for your thoughtful feedback. We’ve heard you and we sincerely apologize for the confusion. **Submissions will remain open until Monday, May 25th midnight**.  Unfortunately, we have **reached capacity for our Tier 2 swag requests** and cannot continue to offer that as of today.  However, **all approved submissions are eligible to receive Tier 1 swag** and have projects reviewed for the ceremony.

**Comment by abdulghanitech** [comment]
>  Hi all! The Education Team, which includes everyone's favorite @juanpflores, is working extremely hard on this event and, of course, reviewing PRs. They are reviewed in random order to ensure there is no bias.

Great! But just wanted to know why it's being reviewed in a random order and not by the sequence. :) I've submitted by PR #1857 2 days ago and I'm waiting for it to be reviewed while newer PRs are getting reviewed. Thanks!

**Comment by brianxfury** [comment]
> @dilipkary @Mohammed-Shoaib @puf17640 let's end this, yeah? This is meant to be a fun event!
> 
> @dilipkary I'll peer-review your PR. Link me to it.
> 
> Edit: @dilipkary reviewed it just now. You're good to go!

my PR is #1309

**Comment by brianxfury** [comment]
> @dilipkary @Mohammed-Shoaib @puf17640 let's end this, yeah? This is meant to be a fun event!
> 
> @dilipkary I'll peer-review your PR. Link me to it.
> 
> Edit: @dilipkary reviewed it just now. You're good to go!

@wrik003 my PR is #1309 Thanks!

**Comment by Aman22sharma** [comment]
> > Hi all! The Education Team, which includes everyone's favorite @juanpflores, is working extremely hard on this event and, of course, reviewing PRs. They are reviewed in random order to ensure there is no bias.
> 
> Great! But just wanted to know why it's being reviewed in a random order and not by the sequence. :) I've submitted by PR #1857 2 days ago and I'm waiting for it to be reviewed while newer PRs are getting reviewed. Thanks!

Yes same question I have also submitted my PR #1570 2 days ago but it is not reviewed yet while new PRs are getting reviewed.

**Comment by puf17640** [comment]
> 👋 Hi all!  The Education Team, which includes everyone's favorite @juanpflores, is working extremely hard on this event and, of course, reviewing PRs.  They are reviewed in random order to ensure there is no bias.

**They are reviewed in random order to ensure there is no bias**

**Comment by elisemoe** [comment]
Hey folks, thanks so much for all of your help! We have a script running on the pull requests with manual review steps for things like images and quotes. There are a few of us doing reviews, so the randomization ensures we're not always running into each other :) We'll be sure to get through them all before the event on June 15th.

**Comment by SkanderHelali** [comment]
Quick question: if the pull request was submitted during the first few hundred PRs, are you still eligible for the Tier 2+ swag? :smile:  Or has that been cancelled given the insane response and number of entries?

Thanks for all you've done regardless, it feels great having any sort of recognition given the circumstances :+1:  :heart:

**Comment by elisemoe** [comment]
> Quick question: if the pull request was submitted during the first few hundred PRs, are you still eligible for the Tier 2+ swag? 😄 Or has that been cancelled given the insane response and number of entries?
> 
> Thanks for all you've done regardless, it feels great having any sort of recognition given the circumstances 👍 ❤️

If your pull request and shipping information were submitted before 2:30 PM PDT on 5/22 you are eligible for Tier 2.

**Comment by dilipkary** [comment]
@mogalvanize  @juanpflores  
why such type of discrimination with me.
I just saw @juanpflores comment on my pr.
I felt again disappointed with Github.
sorry if you are not want to merge my pr it's ok.
I am going to close or delete my pr.
![Screenshot (258)](https://user-images.githubusercontent.com/10993053/82737833-590a9900-9d51-11ea-81a7-c5788675e8fa.png)

**Comment by SkanderHelali** [comment]
@dilipkary that means your PR seems to be done correctly. What is the problem?
It will be merged eventually, there is no point in complaining and watching it 24/7.

This issue should probably be closed, as it was answered an hour ago.
