### ISSUE TITLE
Unable to reopen closed pull request

### ISSUE THREAD

**Issue by inders07** [education/graduation#2386]
The reviewer asked me to make some changes then reopen the PR. I made the required changes but know i don't know how to reopen the PR. Any ideas on how one can do it?

**Comment by Mohammed-Shoaib** [comment]
You can just open a new pull request! :sparkles:

Mine had a non-ascii character (em dash) in #486, I opened a new pull request in #2407.

**Comment by ben-xD** [comment]
The reviewer @juanpflores specifically said to **re-open** the PR. I don't think we can.

**Comment by UtkarshChaurasia** [comment]
I too opened a new pull request #2474 as my previous one was having some errors. Please review it.

**Comment by ArjArav98** [comment]
> The reviewer @juanpflores specifically said to **re-open** the PR. I don't think we can.

So what should we do?

**Comment by juanpflores** [comment]
You can open a new Pull request to get reviewed. Re-open has made some struggles with this amount of PRs

**Comment by bhatshravan** [comment]
Do we need to fill the form out again in this case?
Cause the new form submissions wont get tier 2 and 3 swag right?

**Comment by bdashore3** [comment]
I was going to ask this question as well

**Comment by Vishal1297** [comment]
> Do we need to fill the form out again in this case?
> Cause the new form submissions wont get tier 2 and 3 swag right?

@bhatshravan No form submission can only be done once.

**Comment by sudsj** [comment]
@Vishal1297 are you sure ? If they are linking form with pull requests and they see that the pull request is closed and not merged, will your entry still be eligible ?

**Comment by elisemoe** [comment]
@sudsj @bdashore3 @bhatshravan you do not need to resubmit the shipping form.
