### ISSUE TITLE
New PR still eligible for tier 2 swags?

### ISSUE THREAD

**Issue by kautukkundan** [education/graduation#2631]
My PR #445 had a slight issue about image ratio and I was asked to resubmit. I hope the new PR will still be eligible for Tier 2 swags?

**Comment by ritwikshanker** [comment]
I also have the same doubt as in the comments this thing is striked out.

**Comment by Mohammed-Shoaib** [comment]
Yes based on [this](https://github.com/education/graduation/issues/2314#issuecomment-633104268) comment from one of the maintainers

> Pull requests and shipping information submitted before 2:30 PM PDT on 5/22 are still eligible for Tier 2.

Since your original pull request satisfies this condition, you qualify for the swags!

**Comment by SAHARSH123** [comment]
My PR #726 has been reviewed by @juanpflores it states first review completed but it's not been merged can i know why?

**Comment by elisemoe** [comment]
Thanks, @Mohammed-Shoaib ✨ All initial pull requests and shipping information submitted before 2:30 PM PDT on 5/22 are still eligible for Tier 2.

**Comment by elisemoe** [comment]
> My PR #726 has been reviewed by @juanpflores it states first review completed but it's not been merged can i know why?

Pull requests are all reviewed twice. Once by a script, indicated by the comment from `@juanpflores`. The second review will be one of the team to check images and quotes against our [Code of Conduct](https://github.com/education/graduation/blob/master/CODE_OF_CONDUCT.md).

**Comment by sudsj** [comment]
> Thanks, @Mohammed-Shoaib ✨ All initial pull requests and shipping information submitted before 2:30 PM PDT on 5/22 are still eligible for Tier 2.

Do we have to fill the form again ? I was wondering since the original form is linked to a pull request that is closed and not merged.

**Comment by Aman22sharma** [comment]
@elisemoe @Mohammed-Shoaib I have submitted my PR #1570 before three days after reviewed my PR founded some image pixels issue and that PR is closed now and after resolved the image pixels issue just I have created a new PR #2879  so, Can I qualify for swag?

**Comment by Mohammed-Shoaib** [comment]
@Aman22sharma Yes you do!

**Comment by Mohammed-Shoaib** [comment]
@sudsj No you do not have to fill the form again, they have your data since you filled it once already.

**Comment by elisemoe** [comment]
Here to reiterate @Mohammed-Shoaib 😊

@Aman22sharma I have merged your PR. You will receive swag per the first pull request.
@sudsj you do not need to fill out the form again.

**Comment by Aman22sharma** [comment]
@elisemoe @Mohammed-Shoaib thank you

**Comment by tshradheya** [comment]
I submitted #263 before 20th May but due to image issue I had to submit another one #2358

May I know if I am eligible for swag and also if I need to fill any more form?

**Comment by Mohammed-Shoaib** [comment]
@tshradheya As mentioned in [this](https://github.com/education/graduation/issues/2631#issuecomment-633181645) comment, you do qualify.

**Comment by sharanp98** [comment]
> Here to reiterate @Mohammed-Shoaib 😊
> 
> @Aman22sharma I have merged your PR. You will receive swag per the first pull request.
> @sudsj you do not need to fill out the form again.

Thank you for the clarification. I have one more doubt. I filled the form with the PR link that was not approved. I opened a new PR to fix the image size issue. If I do not fill the form again, how would you make the requirements to ship for the PR that was not originally approved? Please clarify.

**Comment by Mohammed-Shoaib** [comment]
@sharanp98 Just because you created a new PR doesn't mean your GitHub username gets changed :smile: 

They have your data, so they can pull up your form using it, so chillax :relaxed:

**Comment by Ahmeed2m** [comment]
@elisemoe  My pull request was made before 22/5 but there was a problem with linking the form to the pull request and I submitted the form again (after 22/5) and it got merged, So am I still eligible for tier 2, as I did indeed fill both before 22/5 but the script had problems with my form submission
