### ISSUE TITLE
Criteria for Reviewing / Approving PR's

### ISSUE THREAD

**Issue by nedpals** [education/graduation#2845]
Hi, I just observed that most recent ones get accepted/reviewed quickly while some of the earlier ones are not and I was worried that my submission was skipped. Just wondering what's your criteria for reviewing or approving PR's?

**Comment by elisemoe** [comment]
PRs are being reviewed in a randomized order: https://github.com/education/graduation/issues/2314#issuecomment-633102065

Our team is hard to get through them but expect things will take a few days. Thanks for your patience 💖
