### ISSUE TITLE
Accidentally deleted forked repository

### ISSUE THREAD

**Issue by Ashrith-Shetty** [education/graduation#3067]
While making changes to the Pull Request, I accidentally deleted the forked repository and no longer have access to the pull request.
https://github.com/education/graduation/pull/518

Should I go ahead and redo the entire process again?

**Comment by ShaunLWM** [comment]
I think you can pull a push request locally and edit from there.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

If it's too troublesome, feel free to close the pull request and open a new one.

**Comment by saswat01** [comment]
Hey  as long as you have the forked repo in your local machine it should be alright to make changes and PR. Also, feel free to checkout this link https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
I hope it helps you.
