### ISSUE TITLE
github username case sensitive ?

### ISSUE THREAD

**Issue by Ahmeed2m** [education/graduation#3068]
Is the github username from pull request validated against the form submissions, case sensitive?
I filled the form with the username ahmeed2m but my actual github username is Ahmeed2m. hence I received a review in #1809 saying 

`We were not able to find your form submission on our side. Fill a shipping form before we can move on with your revew.`

I think it should not be case sensitive validation. If it's not validated against the username but validated against the email. maybe you should add a notice to fill the form with the github registered email

**Comment by Ahmeed2m** [comment]
@elisemoe  In this comment https://github.com/education/graduation/issues/2631#issuecomment-633181942 I figured that's the script made that review. I filled the form again today because I thought it was manually reviewed. But I'm afraid I will not be eligible for tier 2 now that there is 2 entries for me one with Ahmeed2m (new submission after May 22 ) and old ahmeed2m (old submission before May 22, not detectable from the script because the camel case)

**Comment by juanpflores** [comment]
It is not case sensitive. I'll review what happened with our API 👍

**Comment by realshaunoneill** [comment]
I had the same issue I think.  I've submit another forum as directed in the PR comments.

**Comment by HenriqueChigumane** [comment]
I have submitted twice and I had the same issue on #679.
and don't what I gonna do!

**Comment by Ahmeed2m** [comment]
@juanpflores any update or reason of closing? 

There is three of us who re-submit the form twice because of that script review. Maybe a fill in for what's happening/why is that happening.
