### ISSUE TITLE
Previously submitted PR was closed by team. Am I still eligible for Tier 2?

### ISSUE THREAD

**Issue by sharanp98** [education/graduation#3075]
I had submitted a PR that was eligible for Tier 2 but it was closed due to the profile picture not meeting the size criterion. I have opened another PR and submitted another form but am I still eligible for the Tier 2 rewards?
This was my original PR - https://github.com/education/graduation/pull/1291
My modified PR - https://github.com/education/graduation/pull/3073

The PR was closed only a few hours ago by the Github team. I immediately opened another PR but the README now states new PRs are no longer eligible for Tier 2. Please help

**Comment by markjhvonk** [comment]
Unfortunately this happened to me too... wondering the same thing. 😅

**Comment by JACOBIN-SCTCS** [comment]
Please do something related to this issue @elisemoe @juanpflores

**Comment by aryanrawlani28** [comment]
Hi @sharanp98 & @markjhvonk,
If you've submitted your information before 2:30 PM PDT on 5/22, you are still eligible for T2 rewards, as stated by a member here: https://github.com/education/graduation/issues/2631#issuecomment-633181645

One person before had the same question, and you can view the entire chat here: https://github.com/education/graduation/issues/2631

**Comment by mitulsavani** [comment]
@sharanp98 Since the question is answered in the comment above, could you please close this issue to avoid spam on this thread.

**Comment by sharanp98** [comment]
@aryanrawlani28  Thank you for the clarification. I have one more doubt. I filled the form with the PR link that was **not approved**. I opened a new PR to fix the image size issue. If I do not fill the form again (as mentioned in here https://github.com/education/graduation/issues/2631#issuecomment-633181645), how would you make requirements to ship for the PR that was not originally approved? Please clarify.

**Comment by daylenca** [comment]
@sharanp98 The new Airtable form states that the GitHub staff with update the PR link themselves for previous requests!
