### ISSUE TITLE
Do we need to fill another new form for second pull request ?

### ISSUE THREAD

**Issue by thecoderxman** [education/graduation#3366]
This is my previous PR #627 which had image ratio issues and I've created another another PR #3220 where I updated as per the instructions. Do I need to fill another form for this or will the old form be considered? Will this impact for tier 2 swags? @elisemoe could you please help me with this.

**Comment by charan7386** [comment]
I guess it's not required, old form will be updated by the organizers, because it's stated [here](https://airtable.com/shrmuHxu38ZariKJi)

**Comment by thecoderxman** [comment]
> I guess it's not required, old form will be updated by the organizers, because it's stated [here](https://airtable.com/shrmuHxu38ZariKJi)

Thank you @charan7386 for reaching out , I've just seen it 👍🏻

**Comment by Aurther-Nadeem** [comment]
Hey I’ve got a bit of an issue, I kind of made 2/3 swag requests because I thought you’d have to do a new one when ur pull request changed. Can someone on the team cancel all but one of my shipping requests :).

**Comment by elisemoe** [comment]
> Hey I’ve got a bit of an issue, I kind of made 2/3 swag requests because I thought you’d have to do a new one when ur pull request changed. Can someone on the team cancel all but one of my shipping requests :).

Yes, you're good to go! Thanks @Aurther-Nadeem

**Comment by elisemoe** [comment]
> This is my previous PR #627 which had image ratio issues and I've created another another PR #3220 where I updated as per the instructions. Do I need to fill another form for this or will the old form be considered? Will this impact for tier 2 swags? @elisemoe could you please help me with this.

Nope, no need to fill out a new form!
