### ISSUE TITLE
bogliosimone is in wrong position

### ISSUE THREAD

**Issue by ELChris414** [education/graduation#3431]
The folder 'bogliosimone' is not inside the _data directory.

**Comment by ELChris414** [comment]
Also worth mentioning, in the assets folder there is a photo called fasal.jpg, which shouldn't be there

**Comment by juanpflores** [comment]
Thanks, mate. Will fix 🔨

**Comment by bogliosimone** [comment]
Sorry, my bad. I fixed the problem in this pull request https://github.com/education/graduation/pull/3465
