### ISSUE TITLE
Why my PR is not merged?

### ISSUE THREAD

**Issue by mr687** [education/graduation#3476]
My status is First review completed correctly.

#1837

**Comment by saswat01** [comment]
Hello! I checked your issue and found out maybe checking "My application box" will solve your problem.

**Comment by SoumyaChoubey** [comment]
but mine is all right, still, I am waiting for getting it to merge. :(

**Comment by chayan-chawra** [comment]
Same. Even I am waiting for my PR to be merged #3399

**Comment by vaarigupta** [comment]
I did all the procedure absolutely correct. My PR was not even reviewed yet.

**Comment by aryanrawlani28** [comment]
@mr687, your PR looks fine. The review left by Juan was actually by a script to ensure the basic things are met.

Once that check is completed, your PR will be manually reviewed once again to ensure everything is correct. Then, your PR gets merged.

Since there were 2000+ PRs to review, it will obviously take some time. Your PR looks fine, please be patient. It will get merged soon.

**Comment by surajsahani** [comment]
is all 910 pr will merge till tonight? Many students PR is not reviewed yet. The bellow one is mine.
#2935

**Comment by surajsahani** [comment]
> I did all the procedure absolutely correct. My PR was not even reviewed yet.

can you share your PR link?

**Comment by ShaunLWM** [comment]
Everyone need to stop worrying if their PR is going to be merged. My guess is the staff is going to take the time after closing the application spots to merge all PR. Don't forget the time difference that the staff may be asleep as well.

https://github.com/education/graduation/issues/3545#issuecomment-633509130

**Comment by thejithinmathew** [comment]
Please close the issue since your PR has been merged.

**Comment by jerrycode06** [comment]
Even My PR had reviewed successfully  but it will not merged

**Comment by thejithinmathew** [comment]
> Even My PR had reviewed successfully but it will not merged

Sir, please note that the first review is a Script review. Given the number of applicants, it will take time to look at your PR and merge it. That does not mean your PR will not be merged. Please have patience.

All the PR will be closed before further action.
