### ISSUE TITLE
Clarify what is meant by "special characters"

### ISSUE THREAD

**Issue by lokegustafsson** [education/graduation#348]
Under **3. Add your profile information:**
> Do not use special characters in the template above.

I think this needs to be explained further. Special characters could mean non-ascii, or it could mean some subset of apostrophes, punctuation and escape characters.

**Comment by Nathan-Patnam** [comment]
Especially since people can have "special symbols" in their usernames like dashes or question marks.

**Comment by rabindratamang** [comment]
My institution name has "apostrophe" in it too. So, does it count as a special character?

**Comment by 6a** [comment]
I would assume something along the lines of "Printable ASCII character only" would be more suitable, if that is indeed the case.

**Comment by darkRaspberry** [comment]
yup same issue.
can i use ❤️ this is printable

**Comment by briantical** [comment]
Do emojis count as special characters 🤓

**Comment by DCzajkowski** [comment]
I think @juanpflores can help :)

**Comment by BourgonLaurent** [comment]
Also, does accentuation counts as special characters? Like `é`, `è` or `à`.

**Comment by juanpflores** [comment]
Hey Folks 👋 
As mentioned by @6a any printable ascii character is available. We can do emojis as well ❤️
