### ISSUE TITLE
Tier 2 swag - New PR for change

### ISSUE THREAD

**Issue by LenhardErwan** [education/graduation#3499]
Hi,
I did a first PR (#498) and filled out the first form when the Tier 2 was still available. Except that I made some mistakes on my files, and so I had to do a PR again (#3441).
So I would like to know if I am still eligible to receive my Tier 2 Swag. 

Thank you for your answer and have a nice day everyone ^^

**Comment by ELChris414** [comment]
https://github.com/education/graduation/issues/3075#issuecomment-633225302

Duplicate of #3075 which was answered on that comment.

**Comment by LenhardErwan** [comment]
Oh my bad I didn't see it 😅
Thanks.
