### ISSUE TITLE
---

### ISSUE THREAD

**Issue by aamirams93** [education/graduation#3682]
---
name: Md Aamir
institution: Gulzar Group of Institute
profile_pic: aamirams93.jpg
quote: self confidence is my strength and knowledge is my power
github_user: aamirams93
---
[My data](_data/aamirams93/aamirams93.md)

_Originally posted by @aamirams93 in https://github.com/education/graduation/pull/3664#issuecomment-633614419_

**Comment by ELChris414** [comment]
Hello! You did the process pretty well, just a few mistakes! This is not the proper way to do it, do what you did before but with the changes I suggested in the PR #3664.
