### ISSUE TITLE
Image not showing in _data after merge

### ISSUE THREAD

**Issue by Souvik-py** [education/graduation#3774]
#299 my pr got merged yesterday but my image isn't showing in my folder named Souvik_py 
I'm unable to understand what happened..

Should I upload another one and then open a new pr referencing the previous one?

**Comment by GiselleSerate** [comment]
Seems like what happened is your image is in souvik and your md is in Souvik-py? If you submit another PR, it should probably just move the image into the right folder instead of reuploading.
