### ISSUE TITLE
not merged even after getting reviewed 

### ISSUE THREAD

**Issue by gaurav-chaurasia** [education/graduation#3981]
my PR was reviewed and the reviewer also commented as everything was ok but still not merged
here is the link to my pull request
https://github.com/education/graduation/pull/3500

**Comment by CLiu13** [comment]
Please be patient. GitHub staff are currently working through the queue of reviews.

**Comment by ShaunLWM** [comment]
https://github.com/education/graduation/issues/3476

**Comment by Mohammed-Shoaib** [comment]
@gauranshkumar I see you reopened this issue

Your pull request is perfect! :confetti_ball: @mitulsavani approved the changes. :+1:

However, we (contributors) cannot merge it as we do not have write access. You'll have to wait for a reviewer with _write_ access to merge your pull request.

Based on #4154, the maintainers are on a break for the weekend. They need some rest too! :sleeping: Don't worry, your pull request will be merged soon! :100: 

Till then sit back, relax, and enjoy the weekend :relaxed:

**Comment by gauranshkumar** [comment]
@Mohammed-Shoaib I think you have accidentally mentioned me in the comments as this issue was opened by @gaurav-chaurasia not me 😅

**Comment by Mohammed-Shoaib** [comment]
@gauranshkumar Oops. I am sorry about that, I have updated my comment! :sweat_smile:
