### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by rohitashkmwt** [education/graduation#3982]
I created pull request and it was verified but I found that in graduation/_data directory there is no directory named rohitashkmwt. Please have a look and correct it.

**Comment by rohitashkmwt** [comment]
Link of the pull request is given below:
https://github.com/education/graduation/pull/1999#pullrequestreview-416678728

**Comment by rohitashkmwt** [comment]
Please merge this pull request.

**Comment by CLiu13** [comment]
See https://github.com/education/graduation/pull/1999#issuecomment-633796414

**Comment by rohitashkmwt** [comment]
I have committed photo to the directory. Please have a look and add me to Year Book 2020.

**Comment by CLiu13** [comment]
Thanks for the update. I checked the PR, and you have not yet added a new commit to your branch with the photo. Please see my latest comment for details on how to do so: https://github.com/education/graduation/pull/1999#issuecomment-633798795

**Comment by rohitashkmwt** [comment]
Please reopen the following pull request: 
https://github.com/education/graduation/pull/1999
