### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by rohitashkmwt** [education/graduation#3992]
![rohitashkmwt](https://user-images.githubusercontent.com/43729042/82859951-d8f15880-9f35-11ea-8584-6e0309bdd157.jpg)

**Comment by CLiu13** [comment]
Thanks for the image - however, this is not the correct way to add it to your application for the yearbook. Please see my comment on your current PR: https://github.com/education/graduation/pull/1999#issuecomment-633798795
