### ISSUE TITLE
Query related to swag.

### ISSUE THREAD

**Issue by Devanshk9** [education/graduation#4032]
I found that the reviewers commented on PR's that welcome to the Yearbook and we will sending you a swag but only got this comment-
Welcome to the Class of 2020 Yearbook ✨
and I submitted my PR on 20TH MAY only
So am I eligible for swag as I didn't get that comment?

This is a great initiative by Github.
Thank you
CC: @juanpflores @elisemoe

**Comment by mitulsavani** [comment]
You are certainly still eligible for the swag since you submitted your PR before the deadline; 25th May.

**Comment by Abhishekds94** [comment]
Drop the link to your PR. If it is not approved, one of us can approve it.

**Comment by elisemoe** [comment]
Yes, you are eligible for swag! We had a few scripts running with different messages.

**Comment by ParthKetanDoshi** [comment]
Had a sigh of relief 😃
Thank You @elisemoe!

**Comment by Devanshk9** [comment]
Thanks for solving the query
