### ISSUE TITLE
My PR #3399 has not been merged 

### ISSUE THREAD

**Issue by chayan-chawra** [education/graduation#4154]
Yesterday @juanpflores and @elisemoe asked me to make some changes in the in my PR. I have made the changes and marked it for review but I has not been reviewed yet. Please review and merge my PR #3399

**Comment by elisemoe** [comment]
Hi @chayan-chawra 👋 the team is taking a few days off of reviews (we need some 💤 after the weekend 😊) but will be back at it soon enough ✨ and review yours before the event on June 15th!
