### ISSUE TITLE
Full names could be longer than 18 characters

### ISSUE THREAD

**Issue by lorenzodb1** [education/graduation#422]
Many non-English names can be longer than 18 characters, without containing middle names or second last names. Mine, for instance, is 21 (space included).

It would be amazing if you could allow more than 18 characters, so many more people can have their full name in whatever you need the name for :)

**Comment by puf17640** [comment]
I agree, the length should be extended a bit.

**Comment by ELChris414** [comment]
Absolutely, my full name is 25 characters in English and 23 in Greek.

**Comment by juanpflores** [comment]
Hey folks,
We've heard you. We have uploaded the character limit to 28

**Comment by lorenzodb1** [comment]
Thank you guys ❤️
