### ISSUE TITLE
My PR #3727 has not been merged.

### ISSUE THREAD

**Issue by CET23** [education/graduation#4250]
@omjena27 reviewed and asked me to make some changes in my PR. I have made the changes and marked it for review but I have not been reviewed yet.
Please review and merge my PR #3727

**Comment by ELChris414** [comment]
340 PRs have not been merged. Some like #283 were created 10 days ago. They'll get through them soon enough!

**Comment by Brandonv101** [comment]
@omjena27 How did you mark your PR for review after submission since I am trying to mark mine as for review but I am not sure how to since there isn't an option to reopen the pull request.

**Comment by ELChris414** [comment]
@Brandonv101 you cannot reopen your PR. Just open a new one. If you first PR was before the 26th and you also submitted before the 26th the form, you'll still be eligible for the swag.

**Comment by Mohammed-Shoaib** [comment]
@CET23 Based on #4154, the maintainers are on a break for the weekend. They need some rest too! :sleeping: Don't worry, your pull request will be merged soon! :100:

You do not have to worry about anything. In case your PR is not merged before June 15th (the day of the event), then you can raise an issue! :no_good: 

Till then sit back, relax, and enjoy the weekend :relaxed:

**Comment by Mohammed-Shoaib** [comment]
@Brandonv101 I have reviewed your PR #4254 :blush:

**Comment by omjena27** [comment]
Hey! @CET23 your PR has been merged! Congratulations on graduating 🎓🎉. You're now part of the class of 2020! :)
