### ISSUE TITLE
Airtable Form Response Copy

### ISSUE THREAD

**Issue by MaksimEkin** [education/graduation#4285]
Does anyone know how to find a copy of our response to the Airtable form that we had to fill out for the swag request?

**Comment by puf17640** [comment]
Sadly, I don't think there is a way to check what you submitted.

**Comment by elisemoe** [comment]
Hey @MaksimEkin  👋  If you would like to verify your information, you can fill out our support form and reference Github Education's online graduation event. We're happy to share what we have in the Airtable form for your submission.

https://support.github.com/contact
