### ISSUE TITLE
My approved PR  #4284 is not been merged. 

### ISSUE THREAD

**Issue by Puja7629** [education/graduation#4292]
{New PR, added --- at the beginning and the end of this file #4284}

**Comment by inderpartap** [comment]
Your PR has not been approved yet by a reviewer with write access. Fellow students are reviewing the PRs just to make sure you have everything right before the main reviews.

**Comment by Puja7629** [comment]
@inderpartap Ok! Thanks for the info. When will the main review start?

**Comment by Mohammed-Shoaib** [comment]
@Puja7629 PRs are being reviewed by the volunteers and maintainers, but please understand there are many PRs to review. All PRs will be done before the event i.e., June 15th. If for some reason by then your PR is not merged, then you can raise an issue!

Till then kindly be patient, sit back, relax, and enjoy :relaxed:

**Comment by chandresh189** [comment]
you will soon get a mail if there would be something wrong in the repo, else your pr will be merged

**Comment by Puja7629** [comment]
By mistake, I closed my PR but I reopened it. I hope no issue will be arsing because of my silly mistake? Can you please answer?

**Comment by chandresh189** [comment]
> By mistake, I closed my PR #4284 but I reopened it. I hope no issue will be arsing because of my silly mistake? Can you please answer?
No need to worry, important is that you must have filled the shipment form, pr will be merged soon if there would'nt any issue in the format.

**Comment by Puja7629** [comment]
> > By mistake, I closed my PR #4284 but I reopened it. I hope no issue will be arsing because of my silly mistake? Can you please answer?
> > No need to worry, important is that you must have filled the shipment form, pr will be merged soon if there would'nt any issue in the format.

okay.

**Comment by puf17640** [comment]
just wait, everyone is going to get reviewed 👍
