### ISSUE TITLE
Air table form submitted but received no confirmation 

### ISSUE THREAD

**Issue by harsh1498** [education/graduation#4304]
I submitted my form but I have not seen any email for the copy to my form. I know there is another issue which says this link will be emailed to us, but I don’t see it. Is there anyway to check I have submitted the form just incorrectly maybe?

**Comment by vimalverma558** [comment]
I think, None received confirmation.

**Comment by harsh1498** [comment]
> I think, None received confirmation.

According to issue 4279 [https://github.com/education/graduation/issues/4279], they sent us a copy

**Comment by chayan-chawra** [comment]
Even I haven't received any email regarding the response on the airtable form.
Will the responses be sent after the PR is finally merged??

**Comment by puf17640** [comment]
no info even if the PR is merged

**Comment by juanpflores** [comment]
If you filled the form you're good to go. Unless we reached out to you to provide additional details on the shipping address there shouldn't be anything else we need.
