### ISSUE TITLE
file in the wrong path

### ISSUE THREAD

**Issue by ifrahur** [education/graduation#4345]
@chayan-chawra  files are in the root directory [chayan-chawra](https://github.com/education/graduation/tree/master/chayan-chawra) Please change the file path to _data

**Comment by chayan-chawra** [comment]
@ifrahur I have moved the md file to _data but i am unable to move the image file. Could you please help.

**Comment by chayan-chawra** [comment]
@ifrahur I have successfully moved the files in the _data folder. Please check

**Comment by chayan-chawra** [comment]
Hi @ifrahur could you please tell me why this issue was reopened?
I have already made a PR addressing all the changes and the PR has already received an approving review.

**Comment by ifrahur** [comment]
hey @chayan-chawra .!  the pr is not merged yet.. so as soon as the PR is merged  we'll close this issue..  :smile:
