### ISSUE TITLE
Update on swags

### ISSUE THREAD

**Issue by thecoderxman** [education/graduation#4357]
Any update on shipment of swags?

**Comment by elisemoe** [comment]
No updates yet 😊 swag is still in the production stage and I will post to the readme and soon as we've started shipping. Thanks for your patience! We're working hard to get things rolling.

**Comment by edokan** [comment]
@elisemoe hello,

I do not want to that guy, but I'm going back to my country in three weeks, and I feel like changing delivery address will be an issue. Do you have at least an expected timeline for swags?

**Comment by elisemoe** [comment]
> @elisemoe hello,
> 
> I do not want to that guy, but I'm going back to my country in three weeks, and I feel like changing delivery address will be an issue. Do you have at least an expected timeline for swags?

Hi @edokan 👋 if you can submit your new address to our support form by the end of today, I can update your shipping form. Depending on where you are located, my best guess is that shipping will take longer than 3-weeks. We are about 10-days from shipping and then international takes about 2-3 weeks for arrival.

https://GitHub.com/support

**Comment by TheRaptor001** [comment]
Yeah any updates? 😬

**Comment by amansharma07** [comment]
Hey @TheRaptor001 , This is a closed issue already. Comment [here](https://github.com/education/graduation/issues/4446) if you have any queries. Or I would suggest just wait for the team to update on readme. Hope it helps 😄

**Comment by TheRaptor001** [comment]
> Hey @TheRaptor001 , This is a closed issue already. Comment [here](https://github.com/education/graduation/issues/4446) if you have any queries. Or I would suggest just wait for the team to update on readme. Hope it helps 😄

your comment [here](https://github.com/education/graduation/issues/4446) brought me here 🙄 and now you ask me to go back

**Comment by amansharma07** [comment]
Sorry for the trouble @TheRaptor001 . Just keep an eye on the [Readme](https://github.com/education/graduation/blob/master/README.md) and you'll get the updates.
