### ISSUE TITLE
chayan-chawra in wrong position / Wrong naming of markdown file

### ISSUE THREAD

**Issue by ELChris414** [education/graduation#4363]
The folder `chayan-chawra` should've been in `_data`

EDIT: `chayan.md` should also be renamed to `chayan-chawra.md`

**Comment by ELChris414** [comment]
Just seen #4346, but usually they fix these issues themselves. Leaving the issue open until it's fixed/merged.

**Comment by chayan-chawra** [comment]
Hi, @ELChris414  I have made the PR #4346 after making all the necessary changes like putting the files in the correct directory and naming the files the same as my username and my PR has already been reviewed after I've made these changes. Only it hasn't been merged yet.

**Comment by ifrahur** [comment]
@chayan-chawra as soon as the pr is merged both the issues will be closed..

**Comment by chayan-chawra** [comment]
@ifrahur the PR has been merged
