### ISSUE TITLE
I can't see my data in '_data'

### ISSUE THREAD

**Issue by mmudit30** [education/graduation#4414]
My pull request was successfully merged and now I came back to this repo after the may and i can't see my data folder.
Is it still there or just randomly taken down?

**Comment by chayan-chawra** [comment]
Hi @mmudit30 no data has been removed from the _data folder.
Please use your Github username as the search query.

I just searched your username and your data is present there 😁

**Comment by mmudit30** [comment]
Okay thanks
And thanks to github for the graduation yearbook
