### ISSUE TITLE
Less Than 1 Hour Before Ceremony, not merged

### ISSUE THREAD

**Issue by JanieHuang** [education/graduation#4418]
Hi,

I was approved for my branch to merge after I made some changes, but it's still not merged in. Will it eventually be? Will this effect Swag? Is there even time to make it into the yearbook?

**Comment by elisemoe** [comment]
Hi @JanieHuang 👋  we'll take a look at pull requests after the show. It is too late for the yearbook but if you've filled out the shipment form, we'll still send you something in the mail 🙂

**Comment by juanpflores** [comment]
Merged 👍
