### ISSUE TITLE
Shown wrong username

### ISSUE THREAD

**Issue by AkhilGKrishnan** [education/graduation#4429]
Hey @elisemoe and @juanpflores,
I'm very excited when my username is listed on the "Future Maintainer's Award" section. But my username is incorrectly spelled over there. You were listed as @AKHULGKRISHNAN,  but the correct one is @AkhilGKrishnan.

![DeepinScreenshot_20200615230654](https://user-images.githubusercontent.com/22231095/84690571-52420100-af60-11ea-8261-221be2d4eb52.png)

Thanks

**Comment by elisemoe** [comment]
Hi @AkhilGKrishnan 👋  I'm so sorry to have misspelled your name. I'll make sure it's updated in our notes. Thanks for letting me know.

**Comment by AkhilGKrishnan** [comment]
Thanks @elisemoe
