### ISSUE TITLE
Any Updates on swags?

### ISSUE THREAD

**Issue by UtkarshChaurasia** [education/graduation#4446]

**Comment by amansharma07** [comment]
[#4357](https://github.com/education/graduation/issues/4357) @UtkarshChaurasia You can get the latest update so far on this issue here. Hope this helps 😃

**Comment by elisemoe** [comment]
We’re so close to shipping!! I’ll update the readme as soon as there’s something new. We ran into a few road bumps with the data we collected, and it’s been a slow process of validating addresses and working though our supply chain. Thanks for your patience 😊

**Comment by UtkarshChaurasia** [comment]
Thanks @elisemoe for the update!

**Comment by jasperchua99** [comment]
cool whose gonna be our logistic provider?
