### ISSUE TITLE
How to change the shipping address?

### ISSUE THREAD

**Issue by bring-shrubbery** [education/graduation#4447]
In about a week I'm moving out of the address that I have provided. I don't think the swag will get here by that time, so I was wondering is there a way to change the address that I have provided before?

**Comment by ifrahur** [comment]
#4434 You can have the details updated on the link given in this issue.. I hope this helps you.. 😃

**Comment by bring-shrubbery** [comment]
@ifrahur My bad, should have searched the closed issues 👀
