### ISSUE TITLE
Address change

### ISSUE THREAD

**Issue by berkintosun** [education/graduation#4452]
Hello, I changed my address and I wanted to ask if it is possible for me to change my shipping address for the swags?

**Comment by tshradheya** [comment]
Same query!

**Comment by P-riyanka-prasad** [comment]
i also have Same query!

**Comment by rahulsinha036** [comment]
I have given my university address and my university will not open this year. But I also gave my home address on extra note, I just want my swags on the address written on the extra note. @juanpflores @juanpflores .Please see it, sir.

**Comment by rahulsinha036** [comment]
Any update when the swags will be delivered to us.

**Comment by P-riyanka-prasad** [comment]
how to change the address?

**Comment by juanpflores** [comment]
Hey folks 👋 
We have already printed the shipping labels for all swag shipments. If the case you have is extreme _(package will get destroyed or you will not be able to recover the package)_ we will need you to[ contact our support team](https://support.github.com/contact) with a brief description of your case to review what options we have.
