### ISSUE TITLE
Any update on swag?

### ISSUE THREAD

**Issue by ht0rohit** [education/graduation#4456]
Any update now? It's been 11 more days since the last query 😁

_Originally posted by @ht0rohit in https://github.com/education/graduation/issues/4450#issuecomment-662817619_

**Comment by AkhilGKrishnan** [comment]
@elisemoe and @juanpflores, Any updates regarding this..?

**Comment by edoardottt** [comment]
Updates will be written in the [README.md](https://github.com/education/graduation/blob/master/README.md)
You can subscribe in some website-change updater (or monitor, how you want) to have update on the README.md
There are a lot with free tier and it will track changes every 6,8,12 hours.
Just google `website change monitor`.
Peace :+1:

**Comment by juanpflores** [comment]
Swag will begin shipping next week and is being sent in batches. It is important to consider there are several countries facing shipping alerts that might delay the delivery. 

https://about.usps.com/newsroom/service-alerts/international/welcome.htm

**Comment by NoobSolver** [comment]
@juanpflores What if someone wants to change the address that was filled by us on form because some are shiffted to other place ???

**Comment by ashwinassysh** [comment]
@juanpflores Just to be sure. In which batch will you be dispatching the swags for students who are in US?
Will we get USPS tracking number?

**Comment by AlexanderOMara** [comment]
My Tier 1 swag arrived today! Thanks for the stickers!

**Comment by pranavavva** [comment]
@AlexanderOMara where in the us are you? I’m in nj and haven’t gotten mine yet...

**Comment by AlexanderOMara** [comment]
@pranavavva I'm in New York. IDK what order they send them in, but if it's the same order they used in the ceremony I was probably in the first batch.

**Comment by nyoungstudios** [comment]
Thank you, I am happy to say I received my stickers today too! From the Bay Area.
