### ISSUE TITLE
Swag Shipment form

### ISSUE THREAD

**Issue by pgirikishore** [education/graduation#561]
I think I had given the wrong link to pull request URL in the swag shipment form, hence I have filled the form again. Is that alright?

**Comment by chiniczR** [comment]
> I think I had given the wrong link to pull request URL in the swag shipment form, hence I have filled the form again. Is that alright?

I second the question.
I also submitted the form twice.
I got confused because the PR template said to check that you've filled the form _before_ making the request.

**Comment by puf17640** [comment]
> > I think I had given the wrong link to pull request URL in the swag shipment form, hence I have filled the form again. Is that alright?
> 
> I second the question.
> I also submitted the form twice.
> I got confused because the PR template said to check that you've filled the form _before_ making the request.

you can edit the PR description after filing the request

**Comment by juanpflores** [comment]
You just need to fill the form once. If you have done it twice, there is no problem with it.
