### ISSUE TITLE
What if the swag shipment doesn't deliver at my place.

### ISSUE THREAD

**Issue by darkRaspberry** [education/graduation#660]
Like i don't think i live in a remote place. e commerce like amazon and flipkart deliver shipment effortlessly and easily but i doubt that this shipment might might not reach me.

**Comment by juanpflores** [comment]
We are doing our best to make sure shipments are delivered 📦. For hard to reach locations, it might take more time to deliver.

**Comment by darkRaspberry** [comment]
Yup thanks.
It takes time. Not that issue we have too much time in this coronavirus issue.
I live in INDIA. SO just asking
Thanks
