### ISSUE TITLE
Volunteer for reviewing the requests.

### ISSUE THREAD

**Issue by saarques** [education/graduation#805]
Hey Github Education team, I will be more than happy to volunteer for reviewing the pull requests, if you need any help regarding that, please do tell me! :)

**Comment by Mohammed-Shoaib** [comment]
Yeah! There are many pull requests to review.

I'd be glad to volunteer to review the pull requests as well. Please do tell me if you need help :relaxed:

Thank you for making graduation exciting for us in these challenging times! :mortar_board:

**Comment by 2KAbhishek** [comment]
Would love to be a volunteer as well, if possible.
Great initiative by the GitHub Education team, looking forward to the livestream.

**Comment by chandrikadeb7** [comment]
Hello GitHub Education Team. Would like to volunteer for reviewing PRs if possible. Thanks!

**Comment by puf17640** [comment]
Hello!
I am a student from Austria and I would also like to volunteer for reviewing PRs if this is possible.
Thanks for making this possible!

**Comment by LarrySul** [comment]
hello amazing Github volunteer looking forward to volunteering to help reviewing PRs

**Comment by rabindratamang** [comment]
Hello!

**Comment by darkRaspberry** [comment]
I would also like to volunteer to review pr..
I already started and reviewed as example.

**Comment by anishagg17** [comment]
Hello GitHub Education Team. Would like to volunteer for reviewing PRs if possible. Thanks!

**Comment by CamdanMead** [comment]
I am here to help review PRs if my help is needed at all!

**Comment by meghanabhange** [comment]
Heya GitHub Education Team, 

I would love to volunteer for reviewing :)

**Comment by riodelord** [comment]
Hello!
I am a student from Indonesia and I would also like to volunteer for reviewing PRs if this is possible.
Thanks for making this possible!

**Comment by aryanrawlani28** [comment]
If help is needed, I would like to volunteer too! I am a student in India.

Thanks for such a great initiative!

**Comment by NishantGautam023** [comment]
Hello!
I am a student from Nepal and I would also like to volunteer for reviewing PRs if this is possible.
Thanks for making this possible! :)

**Comment by ryokugyu** [comment]
Hey, I would love to volunteer for reviewing PR's. 
I am also graduating this year.  This is really an exciting opportunity in the middle of a global pandemic.
Thanks for making this possible for graduates like us to make this time interesting.

**Comment by gurkandemir** [comment]
Hi, I am a senior student in Bogazici University, Turkey. I'd be glad to volunteer to review the pull requests as well. Please do tell me if you need help!

Thank you for making graduation exciting for us in this global pandemic! 🎓

**Comment by sBx99** [comment]
Hey Github Education Team! I would also love to volunteer and help review pull requests. I have a year left to graduate but I'd like to be a part of this somehow :))

**Comment by raven-97** [comment]
Hello, I am a senior student from College of Engineering Trivandrum. I'd like to volunteer to review the PR's.

**Comment by Nick-Vazquez** [comment]
Hi GitHub Education Team!

I am a graduating high school student, and would also love to help review PRs!

**Comment by ishvar99** [comment]
Hi, I am a student from Gautam Buddha University and I would like to volunteer the process of reviewing pull requests.

**Comment by TcpAckFrequency** [comment]
Heya! I'd also love to help review the PRs.

**Comment by oldflame** [comment]
I am a student from Northeastern University and would be happy to review some of the Pull Requests. 
Thanks

**Comment by Uyadav207** [comment]
Hey @education Team..
Hope Everyone is Doing Great.
Thanks for making our Quarantine Great...❤ and helping us being  productive and smart.
I am also a Student and Would love to Review PR's  as a Volunteer.

I can help you in : 
- [x] Editing Typos.
- [x] Suggesting Changes.

Thank You,
Happy Hacking 🎉
@Uyadav207

**Comment by DGKSK8LIFE** [comment]
Would also love to review pull requests

**Comment by SulthanNK** [comment]
Hello GitHub Education Team, 

I would like to volunteer for reviewing PRs if possible. 
Thanks for making this possible! :)

**Comment by Berkeley-Reject** [comment]
Hi GitHub education team, I would like to volunteer for reviewing the pull requests, suggest changes, and check for typos.
Thank you very much if you could consider me for doing that.

**Comment by chandresh189** [comment]
Would love to review the requests and suggest changes

**Comment by rahulsinha036** [comment]
> Yeah! There are many pull requests to review.
> 
> I'd be glad to volunteer to review the pull requests as well. Please do tell me if you need help ☺️
> 
> Thank you for making graduation exciting for us in these challenging times! 🎓

Please review mine too. #1541

**Comment by surajsahani** [comment]
Hello GitHub Education Team. 
I  Would love to volunteer for reviewing PRs if possible. 
Thank you!

**Comment by SaiThejeshwar** [comment]
Hi GitHub education team, 
I would like to volunteer for reviewing the pull requests, suggest changes, and check for typos if possible.
Thank you very much!

**Comment by naman360** [comment]
Hey GitHub education team,
I would like to volunteer for reviewing the pull requests and check for typos if possible.
Thank you

**Comment by aryangulati** [comment]
Hello GitHub education team
I would love to volunteer for reviewing PRs and 
Thank you for doing exciting things!!!!

**Comment by underscoreanuj** [comment]
Happy to help

**Comment by Vishal1297** [comment]
Hello Github Education Team
It would be a great opportunity if I get a chance to help. :man_technologist:

**Comment by bratinkundu** [comment]
Hello Github Education Team,
It will be my privilege to help you reviewing the PRs. Looking forward to it.

**Comment by saurabhbazzad** [comment]
Hi Github Education Team. I am a student at Netaji Subhas Institute of Technology. Tell me if help is needed in reviewing PRs.

**Comment by iamHrithikRaj** [comment]
Hey Github Education! Love to see the developer community unit. I would love to help too. :)

**Comment by akhilaku** [comment]
Hello GitHub Education Team. Would like to volunteer for reviewing PR's if possible. Thanks! : )

**Comment by kaiwalyakoparkar** [comment]
Hey Github Education team! I would love t volunteer for reviewing the pull requests

**Comment by KuldeepSingh0** [comment]
Hello Github Education team. It would be one of the great opportunity to become a volunteer. I'm excited for take the responsibility for Github Education team and become a part of them.

**Comment by CrashxZ** [comment]
Hello Github Education team,
I could help in reviewing the pull requests.

**Comment by notmehul** [comment]
Hi there, I would love to help in the process of reviewing pull requests

**Comment by ashwindasr** [comment]
Hello Github Education team! 
Thank you for making graduation exciting for us during these challenging times! 
I would love to volunteer for reviewing PRs, if its possible.
Cheers!

**Comment by juanpflores** [comment]
# Helping other Students

Hey folks 👍 
Many of you have been reaching out about helping to review pull requests. First of all, it is great to see that some of you have already started helping other students 🤝  by adding comments to their submissions. Second, your reviews could help us a lot!

## What can I do 🤔 ?
We found three main errors made in the submissions that you could help others with:

1. Verify their checklist is complete (they have ticked all the items on the checklist and correct tiers. 
2. Check their pull request only modified submission files (2 files) 🗄️ 
3. The profile picture NEEDS to be squared (1:1 or width=height) and has at least 544 pixels 🖼️ 

We still need to verify the info on our side but with this help we can reduce the back and forward time when asking for changes.

Let's make this event AWESOME 🎉 🎓

**Comment by oldflame** [comment]
> # Helping other Students
> Hey folks 👍
> Many of you have been reaching out about helping to review pull requests. First of all, it is great to see that some of you have already started helping other students 🤝 by adding comments to their submissions. Second, your reviews could help us a lot!
> 
> ## What can I do 🤔 ?
> We found three main errors made in the submissions that you could help others with:
> 
> 1. Verify their checklist is complete (they have ticked all the items on the checklist and correct tiers.
> 2. Check their pull request only modified submission files (2 files) 🗄️
> 3. The profile picture NEEDS to be squared (1:1 or width=height) and has at least 544 pixels 🖼️
> 
> We still need to verify the info on our side but with this help we can reduce the back and forward time when asking for changes.
> 
> Let's make this event AWESOME 🎉 🎓

How do we verify if the person has written a post on dev.io?

**Comment by juanpflores** [comment]
We verify that on our end

**Comment by CamdanMead** [comment]
@juanpflores I just have two clarifications, for me and possibly others.

1. Should we add an approving review if it looks good? (I understand that that doesn't actually approve the PR, but is it helpful for you guys?)
2. For the images, to clarify, they can be *bigger* than 544x544 but not smaller?

Thanks!

**Comment by DGKSK8LIFE** [comment]
> @juanpflores I just have two clarifications, for me and possibly others.
> 
> 1. Should we add an approving review if it looks good? (I understand that that doesn't actually approve the PR, but is it helpful for you guys?)
> 2. For the images, to clarify, they can be _bigger_ than 544x544 but not smaller?
> 
> Thanks!

Would also like an answer to this

**Comment by juanpflores** [comment]
Yes to both!

**Comment by DGKSK8LIFE** [comment]
> Yes to both!

Thank you very much for the response!

**Comment by Rishit-dagli** [comment]
Thank you @juanpflores I will start reviewing PRs right away!

**Comment by SulthanNK** [comment]
I have a suggestion for the collaborator & volunteers for those who reviewing PR's.

I just recently saw the Pull Request tab, we're getting a huge number of requests. But, some peoples who done PR's earlier have no errors still not approved 😏 and some people who recently done PR's were getting in.

Now, we have a good number of energetic volunteers who love to help other's students ❤ . So, we can split into 2 or 3 teams by working simultaneously for those people who done PR's earlier and recent ones to get them in 😉

I hope it works well ✌ & I also start reviewing PR's from the earlier one

@juanpflores 

 Let's make this event AWESOME 🎉 🎓

**Comment by kaiwalyakoparkar** [comment]
Hello Github Education team,
I will start reviewing the PR as soon as possible...😊

**Comment by krabhisharma** [comment]
Hii this is Abhishek Kumar from hyderabad I will love to review and give feedback to all that what can be done to better yourself. I am excited to be a part of github Education

**Comment by kaiwalyakoparkar** [comment]
please review #593

**Comment by Souvik-py** [comment]
Would love to volunteer to review peers. There's a lot of them Haven't reviewed yet..
✌🏻

**Comment by saarques** [comment]
This is the first step towards contributing to Open Source folks, let's buckle up and do this! 

#Make_this_event_Awesome :)

**Comment by surajsahani** [comment]
> I have a suggestion for the collaborator & volunteers for those who reviewing PR's.
> 
> I just recently saw the Pull Request tab, we're getting a huge number of requests. But, some peoples who done PR's earlier have no errors still not approved  and some people who recently done PR's were getting in.
> 
> Now, we have a good number of energetic volunteers who love to help other's students  . So, we can split into 2 or 3 teams by working simultaneously for those people who done PR's earlier and recent ones to get them in 
> 
> I hope it works well  & I also start reviewing PR's from the earlier one
> 
> @juanpflores
> 
> Let's make this event AWESOME
Please Review Graduation Year 2020 #1593

**Comment by saarques** [comment]
Everyone, please edit your respective comments and add your Pull requests' number so that we can make sure ours are reviewed too! :)

**Comment by kaiwalyakoparkar** [comment]
#593

**Comment by Souvik-py** [comment]
#299

**Comment by kaiwalyakoparkar** [comment]
> #593

Please review mine as early as possible

**Comment by saarques** [comment]
> > #593
> 
> Please review mine as early as possible

Please don't spam, yours is already getting reviewed!

**Comment by kaiwalyakoparkar** [comment]
> > > #593
> > 
> > 
> > Please review mine as early as possible
> 
> Please don't spam, yours is already getting reviewed!

Please merge it bro!

**Comment by Vishal1297** [comment]
> let's review each other's so that we can make it easy for collaborators to cover up all PR as fast as possible. #1742

**Comment by bsidio** [comment]
Hello GitHub Education Team. I Would love to volunteer for reviewing PRs if possible.

**Comment by ParthKetanDoshi** [comment]
Hello all, this is an awesome initiative! I’d definitely love to contribute to this.

My PR is #2093

**Comment by kaiwalyakoparkar** [comment]
its a great idea! #593

**Comment by kgrv** [comment]
There are many pull requests to review.

I'd be glad to volunteer to review the pull requests as well. Please do tell me if you need help!

**Comment by ParthKetanDoshi** [comment]
If we want to suggest some changes, should we put it as comment or review?

**Comment by kgrv** [comment]
Reviewing would be a better approach, no?

**Comment by saarques** [comment]
Please review only on three points.

1. Checkbox clear
2. Files modifies--2
3. Profile picture clear

Also, some guys here are downloading the images and then checking if the image is of correct size or not, that's not needed, just open the rich diff for the image file in files changed section, the image will open, then right click on it to see the image info and confirm it is Okay, that's it!

**Comment by mitulsavani** [comment]
> Please review only on three points.
> 
> 1. Checkbox clear
> 2. Files modifies--2
> 3. Profile picture clear
> 
> Also, some guys here are downloading the images and then checking if the image is of correct size or not, that's not needed, just open the rich diff for the image file in files changed section, the image will open, then right click on it to see the image info and confirm it is Okay, that's it!
> 
> Again, the image size expected is "minimum" 544x544 pixels. So anyone, who is just reviewing without seeing the picture, refrain from make this statement, "Looks good to me, make the image 544x544 if not done!". You should check if it is more than 544x544 and it is alright otherwise tell them to change it.

Hi @saarques, 

when we essentially right click on the image, it does not give an option to view the image info on mac, what would be the workaround for that? Or am I doing something wrong here?

Let me know
<img width="818" alt="Screen Shot 2020-05-23 at 8 04 11 PM" src="https://user-images.githubusercontent.com/22231691/82744670-94e13680-9d30-11ea-8973-f62895cd23e6.png">

**Comment by saarques** [comment]
Hey @mitulsavani I'm afraid I don't have much idea about how things work in a mac, I work in ubuntu and it gives a clear option to view image info.

Maybe you should try opening the image in new tab and then try the same? Otherwise the last resort would be to download. :/

**Comment by mitulsavani** [comment]
@saarques Thanks for replying, I ended up finding a solution for that 💯

⭐ ⭐ 
**MAC USERS:**

If you are unable to view the image info, download this Google Chrome extension known as [Image Info](https://chrome.google.com/webstore/detail/view-image-info-propertie/jldjjifbpipdmligefcogandjojpdagn?hl=en) to quickly get the image info by right-clicking on the image. 
⭐ ⭐ 

Let's make it happen

**Comment by saarques** [comment]
> @saarques Thanks for replying, I ended up finding a solution for that 100
> 
> star star
> **MAC USERS:**
> 
> If you are unable to view the image info, download this Google Chrome extension known as [Image Info](https://chrome.google.com/webstore/detail/view-image-info-propertie/jldjjifbpipdmligefcogandjojpdagn?hl=en) to quickly get the image info by right-clicking on the image.
> star star
> 
> Let's make it happen

Cool! :)

**Comment by mitulsavani** [comment]
One common problem that I have come across while reviewing the PR's is, there are multiple reviewers commenting and approving(which we should definitely avoid) the same PRs. 
Instead, we can pick other PR and fast forward the process.

**Comment by saarques** [comment]
Yeah, I felt the same, I think it is only a matter of self-restraint.

If anyone sees that there are reviews already available, only add your review if you think the previous review has some glitch to it, otherwise, restraint from re-reviewing already reviewed PR's. That is of no help to anyone.

The motto is to leave a review so that when the education team member sees it, they will know what the problem in the PR is and in which part, so they can close the PR after providing instructions regarding necessary changes.

**Comment by syedjahangirpeeran** [comment]
Hey Github Education Team! I would love to volunteer in reviewing PRs. Thanks.

**Comment by surajsahani** [comment]
Hi, @saarques  Hope you are doing well :)
Can you please help me reviewing my pr. it would be very helpful I have removed unwanted files and fixed image size.
#2935

**Comment by ShaunLWM** [comment]
Would love to help out in reviewing the pull request as well. Thanks!

**Comment by shahshivam058** [comment]
i want to help in reviewing pull request

**Comment by sarnava1** [comment]
Hello @elisemoe @juanpflores,
I am graduating this year and since my PR in this repo has already been merged I would like to volunteer by reviewing the PRs made to the repo as a large no of PRs are being made and together we can help fast track the process. 

Thank you.

**Comment by Mohammed-Shoaib** [comment]
Hey Everyone,

If you would like to contribute and review the pull requests as well, you do not have to _ask_ here. You can just start reviewing yourself! Take a look at #319 for example. :eyes:

If you have questions, then feel free to ask them here.:bulb:

Thanks,
Mohammed Shoaib :unicorn:

**Comment by yashrajjain726** [comment]
Yes, I also want to contribute to Github graduation pull requests and help the developer team of Github.

**Comment by rahulsinha036** [comment]
I will help in reviewing the PR.

**Comment by omjena27** [comment]
Hello GitHub Education Team!
I Would love to volunteer for reviewing PRs if possible.
Thank you for making graduation exciting in these challenging times!<3

**Comment by gautam08** [comment]
> Hey Github Education team, I will be more than happy to volunteer for reviewing the pull requests, if you need any help regarding that, please do tell me!

**Comment by brianxfury** [comment]
Hi Github team, I would like to volunteer as PR reviewer. Thank youuuuu 💗

**Comment by Mohammed-Shoaib** [comment]
@saarques Can you please close this issue?

**Comment by saarques** [comment]
Yep, Thanks everyone for your contribution. 

Good luck and Happy Graduation! :)

**Comment by akhilaku** [comment]
Sir please review #2000 sir, all the PR's after mine has reviewed and
merged.

I have volunteered, but my PR is not reviewed and approved my github
education  team sir.
Please help...

https://github.com/education/graduation/pull/2000
